version: "3.9"
services:
  sd:
    build: .
    ports:
      - "7860:7860"
      - "7861:7861"
    volumes:
      - ../sd-data:/models
      - ../sd-output:/outputs
    devices:
      - "/dev/kfd"
      - "/dev/dri"
# volumes:
  # sd-cache: