version: "3.9"
services:
  sd:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ../sd-data:/models
      - ../sd-output:/outputs
      - ../sd-cache/root_profile:/root
    devices:
      - "/dev/kfd"
      - "/dev/dri"