version: "3.9"
services:
  sd:
    image: stable-diffusion-webui-automatic:dev
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ../sd-models:/sd/models
      - ../sd-outputs:/sd/outputs
      - ../sd-cache/root_profile:/root
      - ../sd-cache/venv:/sd/venv
      - ../sd-cache/repositories:/sd/repositories
      - ../sd-cache/config:/config
    devices:
      - "/dev/kfd"
      - "/dev/dri"